dataset: "telco"

env_params:
  random_seed: 42

train_params:
  test_size: 0.1
  val_size: 0.1
  model_name: "gcn"
  clean: "drop"
  log_dir: "output"
  interpolate_method: null
  shuffle: true
  batch_size: 128
  n_workers: 0
  init_lr: 0.001
  n_epochs: 30
  device: "mps"
  log_every_n_steps: 1
  ckpt_path: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]

model_params:
  window_size: 10
  n_layers: 3
  hidden_dim: 64
  K: 3

predictor_params:
  dataset: "telco"
  ckpt_folder: "output/gcn/version_0"
  n_thresholds: 100
