dataset: "swat"

model_params:
  window_size: 90
  kernel_size: 11
  use_gatv2: true
  feat_gat_embed_dim: null
  time_gat_embed_dim: null
  gru_n_layers: 5
  gru_hid_dim: 600
  forecast_n_layers: 5
  forecast_hid_dim: 600
  recon_n_layers: 5
  recon_hid_dim: 600
  dropout: 0.3
  alpha: 0.2

train_params:
  model_name: "mtad_gat"
  n_epochs: 100
  batch_size: 128
  init_lr: 0.001
  target_dims: null
  device: "gpu"
  n_workers: 10
  log_dir: "output"
  log_every_n_steps: 1
  test_size: 0.1
  val_size: 0.1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  horizon: 1
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  down_len: 10

predictor_params:
  dataset: "telco"
  n_thresholds: 100
  epsilon: 0.8
  ckpt_folder: "output/mtad_gat_optuna_generic_search/mtad_gat_trial_23/version_0/"
