dataset: "telco"

model_params:
  window_size: 512
  kernel_size: 7
  use_gatv2: true
  feat_gat_embed_dim: null
  time_gat_embed_dim: null
  gru_n_layers: 1
  gru_hid_dim: 300
  forecast_n_layers: 3
  forecast_hid_dim: 300
  recon_n_layers: 1
  recon_hid_dim: 300
  dropout: 0.3
  alpha: 0.2

train_params:
  model_name: "mtad_gat"
  n_epochs: 30
  batch_size: 264
  init_lr: 0.001
  target_dims: null
  device: "mps"
  n_workers: 0
  log_dir: "output"
  log_every_n_steps: 1
  test_size: 0.1
  val_size: 0.1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  horizon: 1

predictor_params:
  dataset: "telco"
  target_dims: null
  scale_scores: false
  level: 0.9999
  q: 0.001
  dynamic_pot: false
  use_mov_av: false
  gamma: 0.8
  reg_level: 1
  ckpt_folder: "output/mtad_gat/version_5"

save_path: "saved_models/mtad_gat"
