model_params:
  hidden_dims: [64, 64, 64, 64, 64, 64]
  kernel_size: 2
  dilations: [1, 2, 4, 8, 16, 32, 64]
  latent_dim: 4
  window_size: 512

train_params:
  model_name: "dcvae_compare_preprocess"
  n_epochs: 200
  batch_size: 32
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_dir: "output"
  log_every_n_steps: 1
  test_size: 0.1
  val_size: 0.1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  horizon: 1
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  down_len: 0

predictor_params:
  target_dims: null
  post_process_scores: true
  score_type: "mse"
  ckpt_folder: "output/mtad_gat/version_2"
  n_thresholds: 100
  epsilon: 0.8
  window_size_smooth: 5
  dataset_for_threshold: "val"