model_params:
  window_size: 5
  embed_dim: 64
  out_layer_num: 1
  out_layer_inter_dim: 64
  topk: 15
  heads: 1
  learn_graph: true
  n_features: 51
  negative_slope: 0.2
  dropout: 0.2
  
train_params:
  model_name: "gdn"
  log_dir: "test_swat"
  n_epochs: 200
  batch_size: 512
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_every_n_steps: 1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  horizon: 1
  down_len: 10
  max_std: null
  cutoff_value: null
  labels_widening: false
  monitor: "Loss/val"
  monitor_mode: "min"
  early_stop_patience: 10
  early_stop_delta: 0.001

predictor_params:
  post_process_scores: true
  n_thresholds: 100
  window_size_smooth: 5
  dataset_for_threshold: "val"
  range_based: true
  range_metrics_alpha: 0.5

  score_type: "mse"
  ckpt_folder: "test_swat/gdn/version_0"

  epsilon: 0.8
  target_dims: null

