dataset: "telco"

train_params:
  shuffle: true
  model_name: "gdn"
  batch_size: 128
  n_epochs: 5
  val_size: 0.1
  device: "cpu"
  init_lr: 0.001
  clean: "drop"
  log_dir: "output"
  n_workers: 0
  test_size: 0.1
  log_every_n_steps: 1
  interpolate_method: null
  ckpt_path: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]

model_params:
  window_size: 15
  embed_dim: 64
  out_layer_num: 5
  out_layer_inter_dim: 256
  topk: 5

env_params:
  save_path_pattern: ""
  random_seed: 42
  report: "best"
  load_model_path: ""
  save_path: "msl"

predictor_params:
  dataset: "telco"
  ckpt_folder: "output/gdn/version_1"
  n_thresholds: 100
