model_params:
  window_size: 128
  hidden_size: 256
  n_layers: 7
  bidirectional: true
  rnn_dropout: 0.2
  fc_dropout: 0.1

train_params:
  model_name: "gru"
  log_dir: "test_telco"
  n_epochs: 200
  batch_size: 512
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_every_n_steps: 1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  horizon: 1
  down_len: 0
  max_std: 7.0
  cutoff_value: 30.0
  labels_widening: true
  monitor: "Loss/val"
  monitor_mode: "min"
  early_stop_patience: 10
  early_stop_delta: 0.001

predictor_params:
  post_process_scores: true
  n_thresholds: 1000
  window_size_smooth: 5 
  dataset_for_threshold: "train"
  range_based: true
  range_metrics_alpha: 0.5
  min_precision: 0.0
  score_type: "mse"
  # ckpt_folder: "benchmarks_telco/gru/version_6"
  ckpt_folder: "test_telco/gru/version_0"
