model_params:
  window_size: 512
  hidden_size: 64
  n_layers: 11
  bidirectional: true
  rnn_dropout: 0.1
  fc_dropout: 0.2
  
train_params:
  model_name: "gru"
  n_epochs: 200
  batch_size: 32
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_dir: "test_ute_random_graph"
  log_every_n_steps: 1
  test_size: 0.1
  val_size: 0.1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  horizon: 1
  down_len: 10
  early_stop_patience: 10
  early_stop_delta: 0.000001

predictor_params:
  post_process_scores: true
  n_thresholds: 1000
  window_size_smooth: 5
  dataset_for_threshold: "train"
  range_based: false
  range_metrics_alpha: 0.5
  min_precision: 0.0
  
  score_type: "mse"
  ckpt_folder: "test_ute_random_graph/gru/version_0"

optimization_params:
  study_name: "gru_optimization_ute"
  n_trials: 100
  metric: "vus_pr_mean"
