model_params:
  window_size: 16
  hidden_size: 64
  n_layers: 1
  bidirectional: true
  rnn_dropout: 0.3
  fc_dropout: 0.3
  
train_params:
  model_name: "gru"
  n_epochs: 50
  batch_size: 32
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_dir: "/dataslow/fbello/output/ute/"
  log_every_n_steps: 1
  test_size: 0.1
  val_size: 0.1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  horizon: 1
  down_len: 10
  early_stop_patience: 10
  early_stop_delta: 0.000001

predictor_params:
  n_thresholds: 0
  ckpt_folder: "output/gru/version_0/"
  window_size_smooth: 5
  post_process_scores: false
  score_type: "mse"
  dataset_for_threshold: "train"
  range_based: true
  range_metrics_alpha: 0.5

optimization_params:
  study_name: "gru_optimization_ute"
  n_trials: 100
  metric: "vus_pr_mean"
